apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: upchaar

resources:
  - ns.yaml
  - cm.yaml
  - backend.yaml
  - virtual_vaidhya.yaml
  - test_scanner.yaml
  - frontend.yaml
  - hpa.yaml

