apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2025-02-06T14:35:05Z"
  labels:
    kubernetes.io/metadata.name: upchaar
  name: upchaar
  resourceVersion: "604500"
  uid: 12caf062-1acf-4552-95a0-8add0aeca4fb
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
