apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtual-vaidhya
  labels:
    app: virtual-vaidhya
  namespace: upchaar
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: virtual-vaidhya
  template:
    metadata:
      labels:
        app: virtual-vaidhya
    spec:
      containers:
      - name: virtual-vaidhya
        image: quasarcelestio/upchaar:virtual-vaidhya-v1
        ports:
        - containerPort: 5000
        resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: virtual-vaidhya-service
  namespace: upchaar
spec:
  type: NodePort
  selector:
    app: virtual-vaidhya
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30003